//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPRSGPSServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"E:\\SMS Application Trial\\MessageProces" +
            "sorManager\\HomeSecurityDB.mdf\";Integrated Security=True;User Instance=True")]
        public string HomeSecurityDBConnectionString {
            get {
                return ((string)(this["HomeSecurityDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"E:\\sgr\\Projects1\\Under Develop\\Securit" +
            "y System\\MessageProcessorManager\\HomeSecurityDB.mdf\";Integrated Security=True;Us" +
            "er Instance=True")]
        public string HomeSecurityDBConnectionString1 {
            get {
                return ((string)(this["HomeSecurityDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"E:\\Security System Server 0.0.1\\Messag" +
            "eProcessorManager\\HomeSecurityDB.mdf\";Integrated Security=True;User Instance=Tru" +
            "e")]
        public string HomeSecurityDBConnectionString2 {
            get {
                return ((string)(this["HomeSecurityDBConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"D:\\Security System Server\\MessageProce" +
            "ssorManager\\HomeSecurityDB.mdf\";Integrated Security=True;User Instance=True")]
        public string HomeSecurityDBConnectionString3 {
            get {
                return ((string)(this["HomeSecurityDBConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\GPSTrackingVehicleData." +
            "mdf;Integrated Security=True;User Instance=True")]
        public string GPSTrackingVehicleDataConnectionString {
            get {
                return ((string)(this["GPSTrackingVehicleDataConnectionString"]));
            }
        }
    }
}
